# Generated by Django 4.1.3 on 2023-03-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainTitle', models.CharField(max_length=30, unique=True)),
                ('img1', models.URLField(blank=True)),
                ('UseFor', models.TextField(blank=True, null=True)),
                ('SmallDiscription', models.TextField(blank=True, null=True)),
                ('technologies', models.TextField(blank=True, null=True)),
                ('img2', models.URLField(blank=True)),
                ('Challanges', models.TextField(blank=True, null=True)),
                ('Solution', models.TextField(blank=True, null=True)),
                ('img3', models.URLField(blank=True)),
                ('Conclusion', models.TextField(blank=True, null=True)),
                ('github', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
